"""
Convert polygons.json to a Vectorworks vs.* Python script.

Usage:
    python to_vwx.py [--json polygons.json] [--world-w 44] [--world-h 26]
                     [--origin-x 0] [--origin-y 0] [--out-script build.vwxscript.py]

The generated build.vwxscript.py can be pasted into Vectorworks
File > Scripts > Run Script, or called via the vwx-mcp execute_script tool.

Coordinate mapping:
    pixel origin = top-left
    world origin = bottom-left (Y-up)
    world_x = px_x * (world_w / img_w) + origin_x
    world_y = (img_h - px_y) * (world_h / img_h) + origin_y
    Units are meters; VW internal unit assumed = 1 mm, so we *1000.
"""

import argparse
import json
import os

# Class → solid fill colour (R,G,B 0-255) for Vectorworks
CLASS_COLORS = {
    "water":     (100, 180, 240),
    "meadow":    (120, 210, 100),
    "tree":      (50,  130,  50),
    "path":      (210, 150,  80),
    "sand":      (240, 220, 130),
    "buildings": (80,   80,  80),
}

# Scale 0-255 to VW 0-65535
def to_vw_color(r, g, b):
    return r * 257, g * 257, b * 257


def px_to_world(px, py, img_w, img_h, world_w, world_h, origin_x, origin_y):
    """Return world coords (mm) from pixel coords."""
    wx = px * (world_w / img_w) + origin_x
    wy = (img_h - py) * (world_h / img_h) + origin_y
    return wx * 1000, wy * 1000   # m → mm for VW


def generate_script(
    polygons: dict,
    world_w: float = 44.0,
    world_h: float = 26.0,
    origin_x: float = 0.0,
    origin_y: float = 0.0,
) -> str:
    meta = polygons["meta"]
    img_w, img_h = meta["image_size"]
    classes = polygons["classes"]

    lines = [
        "# Auto-generated by to_vwx.py — do not edit manually",
        "# Paste into VW Script palette or run via execute_script",
        "import vs",
        "",
        f"# Source: {meta['source']}",
        f"# Image size: {img_w}x{img_h} px (rotation: {meta['rotation_deg']}°)",
        f"# World extent: {world_w} x {world_h} m  origin ({origin_x}, {origin_y}) m",
        "",
    ]

    for cls_name, polys in classes.items():
        if not polys:
            continue
        color = CLASS_COLORS.get(cls_name, (128, 128, 128))
        vr, vg, vb = to_vw_color(*color)
        layer_name = f"LA-{cls_name}"

        lines.append(f"# --- {cls_name} ({len(polys)} polygons) ---")
        lines.append(f"vs.NameClass('{layer_name}')")
        lines.append("")

        for poly_idx, poly in enumerate(polys):
            if len(poly) < 3:
                continue
            # Build flat coord list in mm
            world_pts = []
            for px_pt in poly:
                if isinstance(px_pt, (list, tuple)) and len(px_pt) >= 2:
                    wx, wy = px_to_world(
                        px_pt[0], px_pt[1],
                        img_w, img_h, world_w, world_h, origin_x, origin_y
                    )
                    world_pts.append((wx, wy))

            if len(world_pts) < 3:
                continue

            flat = ", ".join(f"{x:.1f}, {y:.1f}" for x, y in world_pts)
            lines.append(f"# {cls_name} polygon {poly_idx + 1}")
            lines.append(f"h = vs.Poly({flat})")
            lines.append(f"vs.SetFPat(h, 1)")  # solid fill
            lines.append(f"vs.SetFillFore(h, {vr}, {vg}, {vb})")
            lines.append(f"vs.SetFillBack(h, {vr}, {vg}, {vb})")
            lines.append(f"vs.SetClass(h, '{layer_name}')")
            lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Convert polygons.json to VW script")
    default_json = os.path.join(os.path.dirname(__file__), "output", "polygons.json")
    default_script = os.path.join(os.path.dirname(__file__), "output", "build.vwxscript.py")
    parser.add_argument("--json", default=default_json, help="Input polygons.json")
    parser.add_argument("--world-w", type=float, default=44.0, help="World width in meters (default: 44)")
    parser.add_argument("--world-h", type=float, default=26.0, help="World height in meters (default: 26)")
    parser.add_argument("--origin-x", type=float, default=0.0, help="World origin X in meters (default: 0)")
    parser.add_argument("--origin-y", type=float, default=0.0, help="World origin Y in meters (default: 0)")
    parser.add_argument("--out-script", default=default_script, help="Output script path")
    args = parser.parse_args()

    with open(args.json, encoding="utf-8") as f:
        polygons = json.load(f)

    script = generate_script(
        polygons,
        world_w=args.world_w,
        world_h=args.world_h,
        origin_x=args.origin_x,
        origin_y=args.origin_y,
    )

    with open(args.out_script, "w", encoding="utf-8") as f:
        f.write(script)

    print(f"Generated {args.out_script}")
    classes = polygons["classes"]
    for cls, polys in classes.items():
        print(f"  {cls}: {len(polys)} polygons -> {len([p for p in polys if len(p) >= 3])} valid")


if __name__ == "__main__":
    main()
